Also I can use BigInteger
Marawie/code-challenges pull request #11
Opened 2023-06-08 16:04 UTC by Marawie

2023-06-08 21:09 UTC, Y0ucandev requested changes

2023-06-08 21:09 UTC, Y0ucandev commented on MultiplyStrings/MultiplyStrings.java
> +        BigDecimal sum = bigDecimal1.multiply(bigDecimal2);
czemu to sie sum nazywa skoro mnozysz ?

2023-06-08 21:30 UTC, Marawie commented on MultiplyStrings/MultiplyStrings.java
> +        BigDecimal sum = bigDecimal1.multiply(bigDecimal2);
pomyłeczka malutka się wkradła, już poprawiłem

2023-06-09 13:19 UTC, Y0ucandev approved these changes

2023-06-09 13:19 UTC, merged