Feature/human readable time
Marawie/code-challenges pull request #7
Opened 2023-06-05 15:43 UTC by Marawie

Fajne zadanie, poczytałem troche o formatowaniu stringów, kiedyś widziałem , że można robić to za pomocą metody replaceFirst(), ale ogarnąłem coś innego i na pewno to jest przydatne :D

2023-06-05 20:50 UTC, Y0ucandev requested changes

2023-06-05 20:50 UTC, Y0ucandev commented on CalculateAvg/CalculateAvg.java
> +    public double findAverage2(int[] array) {
czemu to drugi PR w ktorym widze ten sam kod ?

2023-06-05 20:50 UTC, Y0ucandev commented on DigitDigit/DigitDigit.java
> +            double squaredDigit = Math.pow(digit, digit);
tu znowu kod ktory juz widzialem, sprawdz co sie dzieje z tym bo to wyglada jak duplikat

2023-06-06 13:51 UTC, Marawie commented on CalculateAvg/CalculateAvg.java
> +    public double findAverage2(int[] array) {
wiem, popelniłem bląd, nie przepinałem się do developa tylko tworzylem nowego feature ze starego stąd ten bląd, jeśli sprawdziłeś to jedno zadanie to możesz zamknąć tego PR. Ponadto nie pushowalem od razu tylko commitowałem i przepinałem branche, teraz nie powinno być juz takich cyrków, sorki ze tak wyszlo i za stracony Twój czas

2023-06-06 14:09 UTC, Y0ucandev commented on CalculateAvg/CalculateAvg.java
> +    public double findAverage2(int[] array) {
TO zamknij ten PR ktory trzeba bo ja juz nie wiem ktory to ktory.
Jasna sprawa, bledy sie zdarzaja luz 
Wazne aby go nie powielac :D

2023-06-06 14:26 UTC, Marawie commented
dobra robi sie szefie :D

wt., 6 cze 2023 o 16:09 Y0ucandev ***@***.***> napisał(a):

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In CalculateAvg/CalculateAvg.java
> <https://github.com/Marawie/code-challenges/pull/7#discussion_r1219726986>
> :
>
> > +    public double findAverage1(int[] array) {
>          double avg = Arrays.stream(array).sum() / (double) array.length;
>          return array.length == 0 ? 0 : avg;
>      }
>
> -    public double find_average2(int[] array) {
> +    public double findAverage2(int[] array) {
>
> TO zamknij ten PR ktory trzeba bo ja juz nie wiem ktory to ktory.
> Jasna sprawa, bledy sie zdarzaja luz
> Wazne aby go nie powielac :D
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Marawie/code-challenges/pull/7#discussion_r1219726986>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2GIA3LLUGNGRXMWTNI74KDXJ42YXANCNFSM6AAAAAAY3FAN64>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-11 21:47 UTC, merged